ALTER TYPE "ProctorEventType" ADD VALUE IF NOT EXISTS 'MOBILE_PAGE_LEFT';
ALTER TYPE "ProctorEventType" ADD VALUE IF NOT EXISTS 'MOBILE_NETWORK_OFFLINE';
ALTER TYPE "ProctorEventType" ADD VALUE IF NOT EXISTS 'MOBILE_NETWORK_ONLINE';
